### ISSUE TITLE
Invalid certificate date

### ISSUE THREAD

**Issue by james-s-w-clark** [Destaq/life-calendar#1]
https://www.onlinelifecalendar.com/

Your connection is not private
Attackers might be trying to steal your information from www.onlinelifecalendar.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by Destaq** [comment]
I took the website down, as shown in the docs:
> NOTE: website has been deactivated, as spammers and web crawlers were eating into hosting costs, and there were no donations. You can still clone the repo and run locally.

**Comment by Destaq** [comment]
Website is back up, just not hosted on a custom domain. You can access it here:
https://onlinelifecalendar.herokuapp.com/

Note that there may be up to a 30-second wait time when initially loading the page, as I'm running it on a free Heroku dyno, which auto-sleeps after an hour of inactivity. Subsequent page loads/visits within that session will take the normal time to load, however.
